// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-albums.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_albums_default = defineTool({
  name: "list_albums",
  title: "Listar \xE1lbuns",
  description: "Lista os \xE1lbuns ativos do Le Ville Pet (t\xEDtulo, descri\xE7\xE3o, data e capa).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("albums").select("id,title,description,cover_url,created_at,is_active").eq("is_active", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { albums: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-photos.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_photos_default = defineTool2({
  name: "list_photos",
  title: "Listar fotos",
  description: "Lista fotos ativas publicadas no site. Permite filtrar por p\xE1gina (home, hotelzinho, fotos, transporte).",
  inputSchema: {
    page: z2.string().optional().describe("Filtrar por p\xE1gina onde a foto aparece (ex.: 'home', 'hotelzinho')."),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ page, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("photos").select("id,title,url,pages,is_active,created_at").eq("is_active", true);
    if (page) q = q.contains("pages", [page]);
    const { data, error } = await q.order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { photos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-videos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_videos_default = defineTool3({
  name: "list_videos",
  title: "Listar v\xEDdeos",
  description: "Lista v\xEDdeos ativos publicados no site do Le Ville Pet.",
  inputSchema: {
    page: z3.string().optional().describe("Filtrar por p\xE1gina (ex.: 'home', 'transporte')."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ page, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("videos").select("id,title,url,pages,is_active,created_at").eq("is_active", true);
    if (page) q = q.contains("pages", [page]);
    const { data, error } = await q.order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-site-config.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_site_config_default = defineTool4({
  name: "get_site_config",
  title: "Configura\xE7\xE3o do site",
  description: "Retorna a configura\xE7\xE3o global do site: contatos, redes sociais, textos das p\xE1ginas e modo manuten\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("site_config").select("*").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { config: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-vagas.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vagas_default = defineTool5({
  name: "list_vagas",
  title: "Listar vagas dispon\xEDveis",
  description: "Lista as vagas de emprego ativas publicadas na p\xE1gina 'Trabalhe Conosco'.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("vagas").select("*").eq("is_active", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vagas: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqpyschiqaxgcvvtgjet";
var mcp_default = defineMcp({
  name: "le-ville-pet-mcp",
  title: "Le Ville Pet",
  version: "0.1.0",
  instructions: "Ferramentas do site Le Ville Pet (petshop em Bauru-SP). Permite consultar \xE1lbuns, fotos, v\xEDdeos, vagas e a configura\xE7\xE3o p\xFAblica do site em nome do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_albums_default, list_photos_default, list_videos_default, get_site_config_default, list_vagas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
