// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqpyschiqaxgcvvtgjet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxcHlzY2hpcWF4Z2N2dnRnamV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4ODA4MTAsImV4cCI6MjEwMjQ1NjgxMH0.0xHMq9-HnCLnMjw0RvKJNPEic-zmIg4-pU_z805U2uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});